-- user data insert
INSERT INTO BUCKET_USER (ID, PASSWORD, NAME, EMAIL, MANAGER) 
VALUES ('hong', '1234', 'hongseoyeon', 'hong@naver.com', 'N');
INSERT INTO BUCKET_USER (ID, PASSWORD, NAME, EMAIL, MANAGER) 
VALUES ('hyeon', '1234', 'leehyeonwoo', 'lee@naver.com', 'Y');
INSERT INTO BUCKET_USER (ID, PASSWORD, NAME, EMAIL, MANAGER) 
VALUES ('jeong', '1234', 'jeongjaewon', 'jeong@naver.com', 'N');
INSERT INTO BUCKET_USER (ID, PASSWORD, NAME, EMAIL, MANAGER) 
VALUES ('seok', '1234', 'leeseokdong', 'sdlee@naver.com', 'N');
INSERT INTO BUCKET_USER (ID, PASSWORD, NAME, EMAIL, MANAGER) 
VALUES ('kim', '1234', 'kimsangmin', 'kim@naver.com', 'N');


-- bucket data insert
INSERT INTO BUCKET (ID, TITLE, IMAGE, CONTENTS, WRITER_ID, REG_DATE, RECOMMEND, ACCUESED, ADDRESS) 
VALUES (BUCKET_SEQ.nextVal, 'seoul', 'seoul.jpg', '서울은 끝내준다', 'kim', SYSDATE, 5, 15, '서울시 남산');
INSERT INTO BUCKET (ID, TITLE, IMAGE, CONTENTS, WRITER_ID, REG_DATE, RECOMMEND, ACCUESED, ADDRESS) 
VALUES (BUCKET_SEQ.nextVal, 'PARIS', 'PARIS.JPG', '파리다 파리', 'hong', SYSDATE, 10, 2,'파리 에펠탑');


-- comment data insert
INSERT INTO COMMENTS (ID,BUCKET_ID,CONTENTS,WRITER_ID,REG_DATE)
VALUES (COMMENTS_SEQ.nextVal,1,'서울은 무슨...','jeong',SYSDATE);
INSERT INTO COMMENTS (ID,BUCKET_ID,CONTENTS,WRITER_ID,REG_DATE)
VALUES (COMMENTS_SEQ.nextVal,2,'파리 괜찮네...','hyeon',SYSDATE);
INSERT INTO COMMENTS (ID,BUCKET_ID,CONTENTS,WRITER_ID,REG_DATE)
VALUES (COMMENTS_SEQ.nextVal,1,'지옥불반도...','seok',SYSDATE);


--bookmark data insert
INSERT INTO BOOKMARK (BUCKET_ID, USER_ID)
VALUES (1,'jeong');
INSERT INTO BOOKMARK (BUCKET_ID, USER_ID)
VALUES (2,'jeong');
INSERT INTO BOOKMARK (BUCKET_ID, USER_ID)
VALUES (1,'hong');
INSERT INTO BOOKMARK (BUCKET_ID, USER_ID)
VALUES (2,'seok');