-- user data insert
INSERT INTO BUCKET_USER (ID, PASSWORD, NAME, EMAIL, MANAGER) 
VALUES ('hong', '1234', 'hongseoyeon', 'hong@naver.com', 'N');
INSERT INTO BUCKET_USER (ID, PASSWORD, NAME, EMAIL, MANAGER) 
VALUES ('hyeon', '1234', 'leehyeonwoo', 'lee@naver.com', 'Y');
INSERT INTO BUCKET_USER (ID, PASSWORD, NAME, EMAIL, MANAGER) 
VALUES ('jeong', '1234', 'jeongjaewon', 'jeong@naver.com', 'N');
INSERT INTO BUCKET_USER (ID, PASSWORD, NAME, EMAIL, MANAGER) 
VALUES ('seok', '1234', 'leeseokdong', 'sdlee@naver.com', 'N');
INSERT INTO BUCKET_USER (ID, PASSWORD, NAME, EMAIL, MANAGER) 
VALUES ('kim', '1234', 'kimsangmin', 'kim@naver.com', 'N');


-- bucket data insert
INSERT INTO BUCKET (ID, TITLE, IMAGE, CONTENTS, WRITER_ID, REG_DATE, RECOMMEND, ACCUESED, ADDRESS)
VALUES (BUCKET_SEQ.nextVal, '서울 남산 타워 여행기', '서울시남산.jpg', '서울은 끝내준다. 근처 맛집도 한 몫 했다.', 'kim', SYSDATE, 5, 15, '서울시 남산');
INSERT INTO BUCKET (ID, TITLE, IMAGE, CONTENTS, WRITER_ID, REG_DATE, RECOMMEND, ACCUESED, ADDRESS)
VALUES (BUCKET_SEQ.nextVal, 'PARIS TOUR', '파리에펠탑.jpg', '파리다 파리~', 'hong', SYSDATE, 15, 5,'파리 에펠탑');
INSERT INTO BUCKET (ID, TITLE, IMAGE, CONTENTS, WRITER_ID, REG_DATE, RECOMMEND, ACCUESED, ADDRESS)
VALUES (BUCKET_SEQ.nextVal, '디지털 그 자체, IT 의 성지', '가산디지털.jpg', '가산에 놀러갑시다.', 'jeong', SYSDATE, 12, 7,'가산디지털단지역');
INSERT INTO BUCKET (ID, TITLE, IMAGE, CONTENTS, WRITER_ID, REG_DATE, RECOMMEND, ACCUESED, ADDRESS)
VALUES (BUCKET_SEQ.nextVal, '소환사의 협곡', '그랜드캐니언.jpg', '쿼리문이 미쳐 날뛰고 있습니다.', 'seok', SYSDATE, 5, 2,'그랜드캐니언');
INSERT INTO BUCKET (ID, TITLE, IMAGE, CONTENTS, WRITER_ID, REG_DATE, RECOMMEND, ACCUESED, ADDRESS)
VALUES (BUCKET_SEQ.nextVal, '으리으리 보성 녹차밭', '보성녹차밭.jpg', '보성녹차 만세', 'hong', SYSDATE, 25, 4,'보성 녹차밭');
INSERT INTO BUCKET (ID, TITLE, IMAGE, CONTENTS, WRITER_ID, REG_DATE, RECOMMEND, ACCUESED, ADDRESS)
VALUES (BUCKET_SEQ.nextVal, '부천 상동 시장에서', '시장.JPG', '치느님 영접하고 왔습니다.', 'kim', SYSDATE, 16, 7,'부천 상동시장');

-- comment data insert
INSERT INTO COMMENTS (ID,BUCKET_ID,CONTENTS,WRITER_ID,REG_DATE)
VALUES (COMMENTS_SEQ.nextVal,1,'서울은 무슨...','jeong',SYSDATE);

INSERT INTO COMMENTS (ID,BUCKET_ID,CONTENTS,WRITER_ID,REG_DATE)
VALUES (COMMENTS_SEQ.nextVal,2,'파리 괜찮네...','hyeon',SYSDATE);

INSERT INTO COMMENTS (ID,BUCKET_ID,CONTENTS,WRITER_ID,REG_DATE)
VALUES (COMMENTS_SEQ.nextVal,3,'지옥철...','seok',SYSDATE);

INSERT INTO COMMENTS (ID,BUCKET_ID,CONTENTS,WRITER_ID,REG_DATE)
VALUES (COMMENTS_SEQ.nextVal,4,'소환사의 협곡에 오신 걸 환영합니다...','jeong',SYSDATE);

INSERT INTO COMMENTS (ID,BUCKET_ID,CONTENTS,WRITER_ID,REG_DATE)
VALUES (COMMENTS_SEQ.nextVal,5,'녹차 = green Car...','hyeon',SYSDATE);

INSERT INTO COMMENTS (ID,BUCKET_ID,CONTENTS,WRITER_ID,REG_DATE)
VALUES (COMMENTS_SEQ.nextVal,6,'한입만...','seok',SYSDATE);


--bookmark data insert
INSERT INTO BOOKMARK (BUCKET_ID, USER_ID)
VALUES (1,'jeong');
INSERT INTO BOOKMARK (BUCKET_ID, USER_ID)
VALUES (2,'jeong');
INSERT INTO BOOKMARK (BUCKET_ID, USER_ID)
VALUES (1,'hong');
INSERT INTO BOOKMARK (BUCKET_ID, USER_ID)
VALUES (2,'seok');

commit;