drop table COMMENTS cascade constraints;
drop table BUCKET_USER cascade constraints;
drop table BUCKET cascade constraints;
drop table BOOKMARK cascade constraints;

-- user table create
CREATE TABLE "BUCKET_USER" 
   ("ID" VARCHAR2(20) PRIMARY KEY, 
	"PASSWORD" VARCHAR2(20), 
	"NAME" VARCHAR2(50), 
	"EMAIL" VARCHAR2(50), 
	"MANAGER" VARCHAR2(20),
);

-- bucket table create
 CREATE TABLE "BUCKET" 
   ("ID" INTEGER PRIMARY KEY, 
	"TITLE" VARCHAR2(200), 
	"IMAGE" VARCHAR2(2000), 
	"CONTENTS" VARCHAR2(2000), 
	"WRITER_ID" VARCHAR2(20), 
	"REG_DATE" DATE NULL, 
	"RECOMMEND" INTEGER, 
	"ACCUESED" INTEGER, 
	CONSTRAINT "BUCKET_FK1" FOREIGN KEY ("WRITER_ID")
	  REFERENCES "BUCKET_USER" ("ID") ON DELETE CASCADE
   );

-- bucket sequence create
CREATE SEQUENCE BUCKET_SEQ
MINVALUE 1
INCREMENT BY 1
START WITH 1
NOCACHE
NOORDER
NOCYCLE ;

--comment table create
CREATE TABLE "COMMENTS" 
   ("ID" INTEGER PRIMARY KEY, 
	"BUCKET_ID" INTEGER, 
	"CONTENTS" VARCHAR2(2000), 
	"WRITER_ID" VARCHAR2(20), 
	"REG_DATE" DATE NULL, 
	 CONSTRAINT "COMMENTS_FK1" FOREIGN KEY ("BUCKET_ID")
	  REFERENCES "BUCKET" ("ID") ON DELETE CASCADE, 
	 CONSTRAINT "COMMENTS_FK2" FOREIGN KEY ("WRITER_ID")
	  REFERENCES "BUCKET_USER" ("ID") ON DELETE CASCADE
   );

-- comment sequence create
CREATE SEQUENCE COMMENTS_SEQ
MINVALUE 1
INCREMENT BY 1
START WITH 1
NOCACHE
NOORDER
NOCYCLE ;

-- bookmark table create
CREATE TABLE "BOOKMARK" 
   ("BUCKET_ID" INTEGER NOT NULL, 
	"USER_ID" VARCHAR2(20) NOT NULL, 
	 CONSTRAINT "BOOKMARK_PK" PRIMARY KEY ("BUCKET_ID", "USER_ID"), 
	 CONSTRAINT "BOOKMARK_FK1" FOREIGN KEY ("BUCKET_ID")
	  REFERENCES "BUCKET" ("ID") ON DELETE CASCADE, 
	 CONSTRAINT "BOOKMARK_FK2" FOREIGN KEY ("USER_ID")
	  REFERENCES "BUCKET_USER" ("ID") ON DELETE CASCADE
   );